var hierarchy =
[
    [ "AMenu", "classAMenu.html", [
      [ "LoginMenu", "classLoginMenu.html", null ]
    ] ],
    [ "AttackFlash", "structAttackFlash.html", null ],
    [ "BackgroundMenu", "classBackgroundMenu.html", null ],
    [ "BossTag", "structBossTag.html", null ],
    [ "BottomPassPlatform", "structBottomPassPlatform.html", null ],
    [ "Button", "structButton.html", null ],
    [ "ButtonInfo", "structButtonInfo.html", null ],
    [ "ButtonTag", "structButtonTag.html", null ],
    [ "Color", "structColor.html", null ],
    [ "ComponentMapper", "classComponentMapper.html", null ],
    [ "ConfigManager", "classConfigManager.html", null ],
    [ "ConnectionMenu", "classConnectionMenu.html", null ],
    [ "Damage", "structDamage.html", null ],
    [ "Dash", "structDash.html", null ],
    [ "SqlDB::DB", "classSqlDB_1_1DB.html", null ],
    [ "Dead", "structDead.html", null ],
    [ "EndMenuPage", "classEndMenuPage.html", null ],
    [ "EnemyTag", "structEnemyTag.html", null ],
    [ "Entity", "structEntity.html", null ],
    [ "EntityData", "classEntityData.html", null ],
    [ "EntityDataBuilder", "classEntityDataBuilder.html", null ],
    [ "EntityFactory", "classEntityFactory.html", null ],
    [ "EntityMetadata", "structEntityMetadata.html", null ],
    [ "EntityMetadataRegistry", "classEntityMetadataRegistry.html", null ],
    [ "EntityProperty", "structEntityProperty.html", null ],
    [ "EntitySerializer", "classEntitySerializer.html", null ],
    [ "EntityTypeDetector", "classEntityTypeDetector.html", null ],
    [ "EventManager", "classEventManager.html", null ],
    [ "Eye", "structEye.html", null ],
    [ "Frequency", "structFrequency.html", null ],
    [ "FunctionMotion", "structFunctionMotion.html", null ],
    [ "Game", "classGame.html", null ],
    [ "GameEvent", "structGameEvent.html", null ],
    [ "GameInstance", "classGameInstance.html", null ],
    [ "GameInstanceConditions", "classGameInstanceConditions.html", null ],
    [ "GameInstanceCore", "classGameInstanceCore.html", null ],
    [ "GameInstanceEntities", "classGameInstanceEntities.html", null ],
    [ "GameInstancePhysics", "classGameInstancePhysics.html", null ],
    [ "GameInstancePlayer", "classGameInstancePlayer.html", null ],
    [ "GameInstanceSerialization", "classGameInstanceSerialization.html", null ],
    [ "GameTimer", "classGameTimer.html", null ],
    [ "GraphicsManager", "classGraphicsManager.html", null ],
    [ "GroundCarry", "structGroundCarry.html", null ],
    [ "Health", "structHealth.html", null ],
    [ "Hitbox", "structHitbox.html", null ],
    [ "HomeMenu", "classHomeMenu.html", null ],
    [ "IComponentStorage", "structIComponentStorage.html", [
      [ "ComponentStorage< Component >", "classComponentStorage.html", null ]
    ] ],
    [ "InputControlled", "structInputControlled.html", null ],
    [ "InputFrame", "structInputFrame.html", null ],
    [ "InputHistory", "classInputHistory.html", null ],
    [ "InputManager", "classInputManager.html", null ],
    [ "IsAttacking", "structIsAttacking.html", null ],
    [ "Registry::View< Components >::iterator", "structRegistry_1_1View_1_1iterator.html", null ],
    [ "JoinMenu", "classJoinMenu.html", null ],
    [ "Level", "classLevel.html", null ],
    [ "Lifetime", "structLifetime.html", null ],
    [ "Lobby", "structLobby.html", null ],
    [ "LobbyManager", "classLobbyManager.html", null ],
    [ "LobbyMenu", "classLobbyMenu.html", null ],
    [ "Magazine", "structMagazine.html", null ],
    [ "MaxHealth", "structMaxHealth.html", null ],
    [ "Menu", "classMenu.html", null ],
    [ "Message", "classMessage.html", null ],
    [ "Promotheus::Metrics", "classPromotheus_1_1Metrics.html", null ],
    [ "MovingPlatform", "structMovingPlatform.html", null ],
    [ "Client::NetworkEvent", "structClient_1_1NetworkEvent.html", null ],
    [ "Client::NetworkEventQueue", "classClient_1_1NetworkEventQueue.html", null ],
    [ "NoPassPlatform", "structNoPassPlatform.html", null ],
    [ "ParallaxLayer", "structParallaxLayer.html", null ],
    [ "ParallaxState", "structParallaxState.html", null ],
    [ "ParameterMenu", "classParameterMenu.html", null ],
    [ "Parent", "structParent.html", null ],
    [ "PasswordManager", "classPasswordManager.html", null ],
    [ "PeerInfo", "structPeerInfo.html", null ],
    [ "PlatformTag", "structPlatformTag.html", null ],
    [ "Player", "structPlayer.html", null ],
    [ "PlayerInput", "structPlayerInput.html", null ],
    [ "PlayerInputState", "structPlayerInputState.html", null ],
    [ "PlayerSyncState", "structPlayerSyncState.html", null ],
    [ "PlayerTag", "structPlayerTag.html", null ],
    [ "Position", "structPosition.html", null ],
    [ "PowerUp", "structPowerUp.html", null ],
    [ "PowerUpTag", "structPowerUpTag.html", null ],
    [ "PreviousPosition", "structPreviousPosition.html", null ],
    [ "ProgramArguments", "classProgramArguments.html", null ],
    [ "Projectile", "structProjectile.html", null ],
    [ "ProjectileTag", "structProjectileTag.html", null ],
    [ "ProjectileType", "structProjectileType.html", null ],
    [ "PropertySerializer", "classPropertySerializer.html", null ],
    [ "QueuedMessage", "structQueuedMessage.html", null ],
    [ "Registry", "classRegistry.html", null ],
    [ "ResourceManager", "classResourceManager.html", null ],
    [ "RigidBody", "structRigidBody.html", null ],
    [ "RTypeNetwork", "classRTypeNetwork.html", [
      [ "Client::RTypeClient", "classClient_1_1RTypeClient.html", null ],
      [ "RTypeServer", "classRTypeServer.html", null ]
    ] ],
    [ "ServerEntityId", "structServerEntityId.html", null ],
    [ "SoundManager", "classSoundManager.html", null ],
    [ "Sprite", "structSprite.html", null ],
    [ "SpriteFactory", "classSpriteFactory.html", null ],
    [ "TextBox", "structTextBox.html", null ],
    [ "TextBoxInput", "structTextBoxInput.html", null ],
    [ "TextBoxTag", "structTextBoxTag.html", null ],
    [ "UdpSocket", "classUdpSocket.html", null ],
    [ "Vector2", "structVector2.html", null ],
    [ "Velocity", "structVelocity.html", null ],
    [ "Registry::View< Components >", "structRegistry_1_1View.html", null ],
    [ "WeaponTag", "structWeaponTag.html", null ],
    [ "Weight", "structWeight.html", null ]
];